### ISSUE TITLE
How to add calendar to Google Calendar 

### ISSUE THREAD

**Issue by fabrizioschiano** [ROS-Aerial/community#12]
Hi all, I don't know if it is only my problem but I am not able to add the Working Group calendar to my Google Calendar. 

Could you please share here the URL of the calendar? 

With the following URL I am not able to add it. 

https://calendar.google.com/calendar/u/0/embed?src=c_3fc5c4d6ece9d80d49f136c1dcd54d7f44e1acefdbe87228c92ff268e85e2ea0@group.calendar.google.com&ctz=UTC

Maybe the owner of the calendar could share another URL? Then, I could take care of adding the how to in a PR on [this page](https://github.com/ROS-Aerial/community/blob/master/meetings.md).

**Comment by fabrizioschiano** [comment]
Hi @knmcguire , thanks for your reply! Do you have all the events in your google calendar synched automatically, or you add the events one by one? The latter case works for me too, but I am not able to sync "Add the whole calendar" among my calendars by importing its URL. 
I have the following problem ["Oops, we couldn't create this event, please try again in a few minutes"](https://support.google.com/calendar/thread/796358/help-needed-oops-we-couldn-t-create-this-event-please-try-again-in-a-few-minutes-error?hl=en)

I will try to email the OSRF about this and in the meantime find a solution. If I am successful I will report here since this might be of interest for other people.

**Comment by tfoote** [comment]
This url is the embed url. If you follow that link there's a small button in the bottom right "+ Google Calendar" you can click to subscribe to the calendar.

**Comment by fabrizioschiano** [comment]
@tfoote thanks a lot! It was so hidden I could not see it. Now it works perfectly, thanks.

**Comment by fabrizioschiano** [comment]
Added a quick "how to" in https://github.com/ROS-Aerial/community/pull/14

**Comment by knmcguire** [comment]
awesome! thanks!
