### ISSUE TITLE
REQUEST: New/Change membership for telemething (Mark West)

### ISSUE THREAD

**Issue by telemething** [ROS-Aerial/community#3]
### Request
- Are you looking to become a member?
- Are you looking to move from one Working Group role to another (e.g. member to reviewer)?

User: (at)telemething
Role: member

### Requirements

- [ x] I have reviewed the community governance model / guidelines (https://github.com/{{ORGANIZATION}}/community)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I am actively contributing to 1 or more working group subprojects

### Sponsors (if applicable)
- (at)sponsor
- ...

### List of contributions to the working group
- PRs reviewed / authored
- Issues triaged
- Other relevant project involvement

**Comment by knmcguire** [comment]
Anything you will like to add ? like links or such?
