### ISSUE TITLE
Review existing indoor navigation ROS packages

### ISSUE THREAD

**Issue by botmayank** [ROS-Aerial/community#60]
### Description
Indoor navigation in aerial robotics is a well defined and studied problem. As a first step towards advancing this field, we consider the already exisiting software in this domain. 
This review of indoor navigation ROS packages should include both ROS 1 and ROS 2. 

### Purpose
To create a single reference point for indoor navigation ROS packages suitable for aerial robots

### Approach 
1. Conduct a literature study of available indoor navigation packages
2. Summarise the study in the Indoor Navigation section of  [aerial_robotics_landscape](https://github.com/ROS-Aerial/aerial_robotic_landscape/blob/main/aerial_autonomy_stacks.md)
3. [Optional future work] test some of the packages in simulation 

### Definition of done 
- [ ] Indoor Navigation section created in  [aerial_robotics_landscape](https://github.com/ROS-Aerial/aerial_robotic_landscape/blob/main/aerial_autonomy_stacks.md), showing available packages

**Comment by idorobotics** [comment]
@botmayank I've added a description to this Issue and started working on it.
