### ISSUE TITLE
22 May 2024: Presentation - Flapperdrones

### ISSUE THREAD

**Issue by knmcguire** [ROS-Aerial/community#63]
Date: Wednesday May 22th 2024
Time: 4pm UTC
Topic: Guest presentation about flapper drones
Speaker: @matejkarasek
Title: Flapper Drones: bioinspired platforms for R&D and drone shows, and how we got there
Discourse post: https://discourse.ros.org/t/may-2024-meetings-aerial-robotics/37520/4

**Comment by knmcguire** [comment]
@matejkarasek, any title you have for the presentation?

**Comment by matejkarasek** [comment]
Flapper Drones: bioinspired platforms for R&D and drone shows, and how we got there

**Comment by knmcguire** [comment]
Join information can be found here: https://discourse.ros.org/t/may-2024-meetings-aerial-robotics/37520/4

**Comment by knmcguire** [comment]
Recording can be found here: https://discourse.ros.org/t/may-2024-meetings-aerial-robotics/37520/5
