### ISSUE TITLE
Run Aerostack2 Gazebo example

### ISSUE THREAD

**Issue by botmayank** [ROS-Aerial/community#66]
- [x] Set up Ubuntu 22.04 + ROS2 Humble 
- [x] Install [Aerostack2](https://aerostack2.github.io/_00_getting_started/binary_install.html)  
- [x] Run [AS2 Gazebo project example](https://aerostack2.github.io/_02_examples/gazebo/project_gazebo/index.html) of Gazebo Fortress + AS2
- [ ] Figure out gaps in documentation

**Comment by botmayank** [comment]
Teleop and mission both fail, arm and emergency stop works

![Image](https://github.com/ROS-Aerial/community/assets/5802226/4fc61642-7fc6-465e-acb8-228e8db0d074)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/adc6aabc-7509-4c2f-b1f6-6b7af7741c59)


Also, dependency for keyboard teleop (pysimplegui) should be linked on [Prerequisites section ](https://aerostack2.github.io/_02_examples/index.html#prerequisites) ideally. I think we should also add a T-Mux cheatsheet here. I forgot how to switch tabs in Tmux for example 😅 

```bash
pip install pysimplegui==4.60
```

I'll consolidate fixes once I have the example running and raise a PR for AS2.

**Comment by knmcguire** [comment]
I don't know what @miferco97 preference is but it might be good to start an issue in the aerostack2 github issue tracker as well? Would be good for them to know that this is missing from their standard installation.

**Comment by javilinos** [comment]
Hi @botmayank, could you please provide us with the terminal output of the tmux window nº1: platform ?
We suspect the error might be generating there. Thanks.

**Comment by botmayank** [comment]
@miferco97 @knmcguire I was going to create one but it seems like there's an existing one that can be escalated. 
@javilinos I think the ticket is self explanatory but maybe we can add labels/bump up priority?

https://github.com/aerostack2/aerostack2.github.io/issues/38


@javilinos  thanks for looking into this! Here are other screenshots from last week when the demo didn't work for me:

Not working:
![Image](https://github.com/ROS-Aerial/community/assets/5802226/4a27a351-7eb8-44ce-b426-f546ca5c20f6)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/559f7eca-9381-41cc-91e9-746664b10201)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/546a4797-36df-4ca9-bea9-675639c04df6)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/542a557e-3f09-42e8-9c87-8c6ebcf0e11d)


@javilinos is there a need to restart after any dependency installation for AS2? Today as I booted up my machine and ran the examples, everything just works 😅 
I launched using `./launch_as2.bash -t` and ran the mission using `python3 mission.py` in the relevant Tmux term and it just worked! After the mission I could use teleop as well.
I even tried to directly run teleop instead of the mission by using `stop.bash` and then starting again and trying teleop directly, that too works.

The only reason for a difference I can think of is that when I first ran those examples last week I didn't have pyqtgui installed initially, and then after installing I didn't restart the machine. Is that needed?

Today's screenshots of example working 😄 


![Image](https://github.com/ROS-Aerial/community/assets/5802226/42bcd06a-86c2-40ce-9833-d7e14dd015aa)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/fea832fe-3e15-410e-9bb1-13abf41522e5)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/5d3053bf-2982-4f7e-ac14-4b3d22e70adb)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/40c0f3e7-72b7-4096-836c-4ba80ca854a8)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/c7e74841-dc0d-404a-9199-566d7be26d9f)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/68195fb4-125e-419c-909f-3ce0b2eb2c5f)
![Image](https://github.com/ROS-Aerial/community/assets/5802226/2896ea70-e74e-4859-a836-4fbffdd8a187)

@miferco97 At this point I don't know if there's a need to open a separate ticket for the behaviour I observed last week since I'm not sure how to replicate it and all I have are the other screenshots I've shared above 😕 Any suggestions?

**Comment by miferco97** [comment]
Hi @botmayank, we have not been able to replicate this, so I think we should move on. We are aware that the install guide should explicitly include the pysimplegui dependency to avoid these bugs. 
If you could collect all the things that should be documented in more detail that would be great!!!

**Comment by botmayank** [comment]
@miferco97 sure, will do, I'll close this for now as we've decided to use GZ-Harmonic + ROS2 Humble as our base stack. I'm trying this out next: https://aerostack2.github.io/_03_aerial_platforms/_gazebo_simulation/index.html#installation
