### ISSUE TITLE
19 June 2024 - Presentation Meeting - New flight controllers

### ISSUE THREAD

**Issue by knmcguire** [ROS-Aerial/community#68]
Date: Wednesday May 19th 2024
Time: 4pm UTC
Topic: ROS platform
Speaker: @khaledelmadawi 
Title: New Generation of Flight Controllers

**Comment by knmcguire** [comment]
@khaledelmadawi could you give us a title of your presentation?

**Comment by khaledelmadawi** [comment]
New Generation of Flight Controllers

**Comment by knmcguire** [comment]
Meeting is announced here: https://discourse.ros.org/t/june-2024-meetings-aerial-robotics/37987/3
