### ISSUE TITLE
REQUEST: New/Change membership for (Aarsh Thakker)

### ISSUE THREAD

**Issue by aarsht7** [ROS-Aerial/community#7]
### Request
- [x]  Are you looking to become a member? 
- Are you looking to move from one Working Group role to another (e.g. member to reviewer)?

User: (at)aarsht7
Role: member

### Requirements

- [x] I have reviewed the community governance model / guidelines (https://github.com/{{ORGANIZATION}}/community)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ ] [^1] I am actively contributing to 1 or more working group subprojects

### Sponsors (if applicable)
- (at)sponsor
- ...

### List of contributions to the working group
- PRs reviewed / authored 
  nothing much. just solving one small [bug](https://github.com/ros-controls/ros_controllers/pull/589) that I faced in past 
- Issues triaged
- Other relevant project involvement
 [natnet-4 based ros driver for optitrack](https://github.com/L2S-lab/natnet_ros_cpp) [Actively maintained]
 member [mocap4ros2](https://github.com/MOCAP4ROS2-Project)

 Looking forward to join my first ros wg (if I qualify 😃 ). 
 I have started working with the drones actively just couple of months ago. (mostly with cf2.1 and couple of dji's TT)

[^1]: I have been actively following ros wg just from past 6-8 months. Not much in contribution so far, But I have some other relevant projects that might fill the void. Also many other ros related projects that are not publicly available (yet).

**Comment by knmcguire** [comment]
Hi! Pretty much open for anybody at this moment that is interested! We don't have any hard requirements at the moment but if you show up to the meetings occasionally and give feedback on discourse or this github, that is all good in our book!

Does this PR look good to you? https://github.com/ROS-Aerial/community/pull/8 Some people also added some links to their names or affiliations as well.

**Comment by aarsht7** [comment]
Hello Kimberly, Yes it looks good to me 👍🏻
