### ISSUE TITLE
11 Sep 2024 - Presentation Meeting - Aerial Robotic simulator survey

### ISSUE THREAD

**Issue by knmcguire** [ROS-Aerial/community#72]
Date: Wednesday September 11th 2024
Time: 4pm UTC
Topic: The current state of Aerial Robotic Simulators
Speaker: @gsilano 
Title: Are Robotic Simulators a Solved Problem? Criteria for Selection and Customization
Recording info found here: https://discourse.ros.org/t/september-2024-meetings-aerial-robotics-back-from-summer/39383/5

**Comment by knmcguire** [comment]
@gsilano Would you know a preliminary title for presentation already?

**Comment by gsilano** [comment]
Are Robotic Simulators a Solved Problem? Criteria for Selection and Customization

**Comment by gsilano** [comment]
Meeting is announced here: https://discourse.ros.org/t/september-2024-meetings-aerial-robotics-back-from-summer/39383

**Comment by knmcguire** [comment]
Thanks! I need to add this to the top issue

**Comment by knmcguire** [comment]
The recording and slides  can be found here: https://discourse.ros.org/t/september-2024-meetings-aerial-robotics-back-from-summer/39383/5. Thanks @gsilano !
