### ISSUE TITLE
20 Nov 2024 - Presentation meeting - The new Duckiedrone

### ISSUE THREAD

**Issue by knmcguire** [ROS-Aerial/community#76]
Date: Wednesday November 20th 2024
Time: 4pm UTC
Topic: "Introducing the DD24: Duckietown's latest platform for learning aerial robotics"
Discourse URL: https://discourse.ros.org/t/aerial-robotics-meeting-20th-of-november-2024/40454

**Comment by knmcguire** [comment]
@Tuxliri Do you have a priliminary title or is 'the new duckie drone' fine?

**Comment by Tuxliri** [comment]
Yes! "Introducing the DD24: Duckietown's latest platform for learning aerial robotics".

Excited to present this to the community!

**Comment by knmcguire** [comment]
Thanks! I'll make the ROS discourse announcement soon

**Comment by knmcguire** [comment]
The join information can be found on ROS discourse: https://discourse.ros.org/t/aerial-robotics-meeting-20th-of-november-2024/40454

**Comment by knmcguire** [comment]
Recording and slides can be found here: https://discourse.ros.org/t/aerial-robotics-meeting-duckiedrone-nov-20-2024/40454/3
