### ISSUE TITLE
REQUEST: New membership for Srivenkateshwar

### ISSUE THREAD

**Issue by Srivenkateshwar** [ROS-Aerial/community#79]
Request
Are you looking to become a member? 👍🏼 Yes
Are you looking to move from one Working Group role to another (e.g. member to reviewer)? Member
User: Srivenkateshwar
Role: member

Requirements
Yes

Sponsors (if applicable)
(at)sponsor
...
List of contributions to the working group
PRs reviewed / authored
Issues triaged
Other relevant project involvement
I am currently involved in developing a drone flight controller and also working as a ROS2 projects . I am interested in joining a working group where I can contribute my skills and expertise.🙂

**Comment by knmcguire** [comment]
Hi! Sure I can add you. What is your full name and affiliation?

**Comment by Srivenkateshwar** [comment]
Full name : Srivenkateshwar Iyer
Affiliation : Currently working at e-Yantra

**Comment by knmcguire** [comment]
Hi! You have been added. Just mind that we are now on a summer hiatus so we will recommence meetings on September 11th. Keep an eye on the ROS discourse for this.
