### ISSUE TITLE
Setup Aerostack2 1.1.0 with GZ Harmonic

### ISSUE THREAD

**Issue by botmayank** [ROS-Aerial/community#81]
Install AS2 from source and setup Aerostack 1.1.0 with Gazebo Harmonic + ROS2 humble natively on Ubuntu 22.04. Run default gz example.

**Comment by botmayank** [comment]
Followed [Aersostack GZ Harmonic Setup](https://aerostack2.github.io/_03_aerial_platforms/_gazebo_simulation/index.html#installation)

and [Aerostack Source Install](https://aerostack2.github.io/_00_getting_started/source_install.html#getting-started-ubuntu-installation-source)

There don't seem to be any errors in the terminal but Gazebo doesn't launch from the launch scripts. 

![Image](https://github.com/user-attachments/assets/101ac08e-977b-4b5c-a661-ac840732495b)
![Image](https://github.com/user-attachments/assets/0e5d2894-56e0-4e82-9cc5-9d194eb08e5c)

Commands applicable for my setup that I used:

```bash
# Source AS2
source /media/mayank/HDD1/3_MJ_Projects/5_ROS_Aerial/2_Indoor_Nav/2_Aerostack2/aerostack2_ws/install/setup.bash --extend

# go to project gazebo repo
cd /media/mayank/HDD1/3_MJ_Projects/5_ROS_Aerial/2_Indoor_Nav/2_Aerostack2/project_gazebo

# Platform launch
ros2 launch as2_platform_gazebo platform_gazebo_launch.py namespace:=drone0 simulation_config_file:=sim_config/world.json


# Simulation launch
ros2 launch as2_gazebo_assets launch_simulation.py headless:=true verbose:=true run_on_start:=false  use_sim_time:=true simulation_config_file:=sim_config/world.json
```

I noticed a minor correction in the platform launch, the arg should be `simulation_config_file` and not `config_file` as per the docs. 

@miferco97 is there any obvious step I'm missing?

**Comment by miferco97** [comment]
Hello, Please create an issue in aerostack2 repository with this problem and acknowledge the bug you have found.

**Comment by botmayank** [comment]
I don't know what happened, when I launched GZ sim manually and opened any example, with the 2 previous ros2 launch commands running, I could see the drone 🤦 

Also, I realized that instead of individually launching, a better way to launch would be using the cool tmux session files you've provided in project_gazebo since they seemed to be compatible, this approach works and teleop is also working!

```bash
cd /media/mayank/HDD1/3_MJ_Projects/5_ROS_Aerial/2_Indoor_Nav/2_Aerostack2/project_gazebo
./launch_as2.bash -t
```

I think I'm finally done with a relatively painless setup of GZ Harmonic + AS2 1.1.0 with ROS2 Humble 😄 



![Image](https://github.com/user-attachments/assets/4807ef27-95ea-47dd-930d-faff0767f076)

**Comment by botmayank** [comment]
@miferco97 created this https://github.com/aerostack2/aerostack2/issues/638
